### ISSUE TITLE
the float type is unbound in a simple program

### ISSUE THREAD

**Issue by LuKuangChen** [facebookincubator/cinder#42]
### What version of Static Python are you using?

9965302
2021-07-15

### What program did you run?

```python
# float_unbound.py

def f(x: float):
    reveal_type(x)
```

### What happened?

The variable `x` has type `dynamic`.

```
compiler.static.TypedSyntaxError: reveal_type(x): 'dynamic', 'x' has declared type 'dynamic' and local type 'dynamic'
```

### What should have happened?

We expected that the variable `x` has type `float` because of the annotation `x: float`. The function `float` has a
type and `float(1)` has the type `Exact[float]`

**Comment by DinoV** [comment]
This is currently due to a combination of behaviors.  First, we treat a `float` annotation as `float | int` because the Python type checkers treat `int` as being compatible with `float`.  We then treat arguments which are declared as unions as dynamic because we don't support runtime type checking of them, so we can't keep them typed otherwise the compiler could narrow through isinstance checks incorrectly.  If we solved the second issue we'd then report this as `int | float`.

**Comment by carljm** [comment]
Closing this as a special case of #49
